name: wavekeeper
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  printing: ^5.13.4
  pdf: ^3.11.1
  dio: ^5.7.0
  scrollable_positioned_list: ^0.3.8
  http: ^1.2.2
  intl: ^0.19.0
  audioplayers: ^6.1.0
  supabase_flutter: ^2.8.0
  file_picker: ^8.1.3
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.2
  music_visualizer: ^1.0.4


flutter_native_splash:
  color: "#800080" # Cor de fundo da splash screen
  image: assets/logoWave.png # Caminho da imagem de splash
  android: true # Habilita a splash screen para Android


flutter_icons:
  image_path: "assets/logoWave.png" # Logo sem fundo
  ios: true # Habilita para iOS
  remove_alpha_ios: true # Remove a transparência para iOS
  android: true # Habilita para Android
  adaptive_icon_background: "#800080" # Cor de fundo roxa para ícone adaptativo
  adaptive_icon_foreground: "assets/logoWave.png" # Logo sem fundo para ícone adaptativo


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
   - assets/logoWave.png
   - assets/favoritas.jpg
   - assets/Musicas.png
   - assets/Beats.png
   - assets/Assinatura.png
   - assets/logoFundo.png


  